#ifndef __DBUTILITYH__
#define __DBUTILITY_H__

#define DBRECORDHEADER 8
#define DBPAGEHEADER 64
#define DBFILEHEADER 10000
#define DBPAGE 8192
#define BUFFILEMAX 100
#define ATTRLENGTHMAX 32
#define ATTRMAX 30

#define DBOK 0
#define CREATEFILEFAILURE -1
#define FILEEXIST -2
#define FILENOTEXIST -3
#define FILENOTOPEN -4
#define NOTSETFILEHEADER -5
#define NOSUCHATTRIBUTE -6
#define RECORDLENGTHERROR -7
#define PRIMARYKEYERROR -8
#define RECORDNOTEXIST -9
#define PAGEIDOVERFLOW -10
#define RIDOVERFLOW -11
#define NOSUCHATTR -12
#define ATTRNAMETOOLONG -13
#define FOREIGNATTRNAMETOOLONG -14
#define FOREIGNFILENAMETOOLONG -15
#define DBEXISTS -16
#define DBNOTEXISTS -17
#define MULTIPLEDBCREATE -18
#define CREATEFILEPATHERROR -19
#define ATTRNUMNOTEQUAL -20
#define DBNOTCHOOSE -21

#endif
